wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.34
    code_path: code/use_cases/ml_apps/chemprop/main/web.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
